<?php
	return array(
		/**********水印配置项**********/
		//水印图路径
		'WATER_IMAGE'=>'./water.png',
		//水印位置
		'WATER_POS'=>9,
		//水印透明度
		'WATER_ALPHA'=>60,
		//JPEG图片压缩比
		'WATER_COMPRESSION'=>80,
		//水印文字
		'WATER_TEXT'=>'HouDunWang.com',
		//水印文字旋转角色
		'WATER_ANGLE'=>0,
		//水印文字大小
		'WATER_FONTSIZE'=>30,
		//水印文字颜色
		'WATER_FONTCOLOR'=>'#670768',
		//水印文字字体文件(写入中文字时需使用支持中文的字体文件)
		'WATER_FONTFILE'=>'./font.ttf',
		//水印文字字符编码
		'WATER_CHARSET'=>'UTF-8',
	)
?>